sudo: false

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

language: node_js
node_js:
- node
- lts/*
cache:
  timeout: 1800
  yarn: true
  directories:
  - node_modules
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent
notifications:
  slack:
    rooms:
      secure: bJm6Pq65j309CCLLBHYiRE+uyhHxx8NZgxm1YqIC2326DCWgP2seznmkcFoVasxHvguiYE/PLZC8Y8Hs8induQ2u47Cs7ioBH8LVxm78qxvTUie22pN3P/bHaI3r/7Vbcelwy/x+Sy3lMIig0s4l+TnQV1OS8CgUaXokdrC08qeknseckRjTLKvGXDpYkkGMPZQCdOjZXSG+LDDSueAEHGoMBk3ASJsRWxuNW9kAr+/p430RR3WNY/veQ8nvHU/fzDTBVEao62ABs4Dig88QkRb3Dd01C0woJUayFREuEGAKlX5xbj5mwO8j8zJbk92VfWGROXbrlwfn70VpsbIvjuJiMcWr1nD9WHf/FXH5jcoG+JgGwADKzaObUAXq+bKwUpW85r3cPcg9w8ybnu5Py2YnQC/QFVlZmWQYsIqcPqP1PwuVjcOZJr1M2HZ33ZSv3k7NMIROvjtaWdBGDhXqltdYMynHXfN+IMA67vyVq7ek6hELFjzfKrBuiD63v/U0Tr0AWhWsf2AnpSHYif+Bek/V+XYh3cSN4uXgqGEGC+lU+T3Eqf5WIgvTfG4LVtmrPYnmgAsZUzoLqFqUZnPHMOMJjD/uKPD8m5SEorfj4Nue/nIaZ08IPqEV0MTio165sOX0tizbZZTXHv/MiZsCPGNW/KxFDXWfckTeLC5+6sw=
  email: false
